pretrained_base_model_path: "path/sd-image-variations-diffusers"
pretrained_vae_path: "path/sd-vae-ft-mse"
image_encoder_path: "path/sd-image-variations-diffusers/image_encoder"
denoising_unet_path: "path/denoising_unet.pth"
pose_guider_path: "path/poctr.pth"
motion_module_path: "path/motion_module.pth"

inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'
